test2020-03-28 18:19:56,211 - connecting to mq gcd2
2020-03-28 18:19:56,219 - Pika version 1.1.0 connecting to ('192.168.99.100', 5672)
2020-03-28 18:19:57,239 - Socket failed to connect: <socket.socket fd=616, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 51900)>; error=10061 (Unknown error)
2020-03-28 18:19:57,240 - TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.99.100', 5672))
2020-03-28 18:19:57,242 - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2020-03-28 18:19:57,243 - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - None.
2020-03-28 18:19:57,245 - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - None
2020-03-28 18:19:57,246 - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - None
2020-03-28 18:19:57,246 - Error in _create_connection().
Traceback (most recent call last):
  File "E:\nishikant project\DOCKER\Nexus\venv\lib\site-packages\pika\adapters\blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
gcd gc dgc dgc dgc dg cgd cg