test2020-03-28 18:19:56,192 - connecting to mq upstream
2020-03-28 18:19:56,221 - Pika version 1.1.0 connecting to ('192.168.99.100', 5672)
2020-03-28 18:19:57,224 - Socket failed to connect: <socket.socket fd=300, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 51901)>; error=10061 (Unknown error)
2020-03-28 18:19:57,226 - TCP Connection attempt failed: ConnectionRefusedError(10061, 'Unknown error'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.99.100', 5672))
2020-03-28 18:19:57,226 - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error')
2020-03-28 18:19:57,227 - AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - None.
2020-03-28 18:19:57,228 - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - None
2020-03-28 18:19:57,228 - Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(10061, 'Unknown error'); first exception - None
2020-03-28 18:19:57,229 - Error in _create_connection().
Traceback (most recent call last):
  File "E:\nishikant project\DOCKER\Nexus\venv\lib\site-packages\pika\adapters\blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
UPUPUPU UPUPUPU UPUPUPUP
abcd ancg cbdh chd  chd  chd cbh